name: ShadowTrace
version: '${version}'
main: no.vestlandetmc.shadowtrace.ShadowTrace
api-version: '1.21'
load: POSTWORLD
authors: [ Baktus_79 ]
description: Trace and hunt for x-rayers.
website: https://www.vestlandetmc.no
dependencies:
  server:
    CoreProtect:
      load: BEFORE
      required: true